# Generated by Django 5.2 on 2025-04-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Company Logo')),
                ('address', models.TextField(verbose_name='Address')),
                ('locations', models.TextField(blank=True, help_text='Enter one location per line', verbose_name='Branch Locations')),
                ('phone', models.CharField(max_length=50, verbose_name='Contact Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Contact Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='Tax/VAT Number')),
                ('registration_number', models.CharField(blank=True, max_length=50, verbose_name='Registration Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Information',
                'verbose_name_plural': 'Company Information',
            },
        ),
    ]
