# Generated by Django 5.2 on 2025-04-22 09:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_sale_sales_sale_invoice_78d822_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['invoice_number'], name='sales_sale_invoice_78d822_idx'),
        ),
    ]
