# Generated by Django 5.2 on 2025-04-21 04:57

from django.db import migrations

def add_initial_data(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    Brand = apps.get_model('products', 'Brand')

    # Add Categories
    categories = [
        ('Laptops', 'Portable computers including notebooks and ultrabooks'),
        ('Smartphones', 'Mobile phones with advanced computing capability'),
        ('Tablets', 'Portable touchscreen computers'),
        ('Desktop PCs', 'Traditional desktop computers and workstations'),
        ('Monitors', 'Computer displays and screens'),
        ('Printers', 'Printing devices including inkjet and laser printers'),
        ('Networking', 'Network equipment including routers and switches'),
        ('Storage', 'Data storage devices including hard drives and SSDs'),
        ('Accessories', 'Computer and phone accessories'),
        ('Gaming', 'Gaming devices and accessories'),
    ]

    for name, description in categories:
        Category.objects.create(name=name, description=description)

    # Add Brands
    brands = [
        ('Apple', 'Manufacturer of Mac computers, iPads, and iPhones'),
        ('Samsung', 'Electronics manufacturer of phones, tablets, and displays'),
        ('Dell', 'Computer hardware company specializing in PCs and laptops'),
        ('HP', 'Hewlett-Packard - computers, printers, and technology solutions'),
        ('Lenovo', 'Computer manufacturer of laptops, desktops, and tablets'),
        ('ASUS', 'Computer hardware and electronics company'),
        ('Acer', 'Hardware and electronics corporation'),
        ('LG', 'Electronics company producing monitors and devices'),
        ('Microsoft', 'Software and hardware technology company'),
        ('Sony', 'Electronics and gaming company'),
        ('Intel', 'Processor and computer component manufacturer'),
        ('AMD', 'Processor and graphics card manufacturer'),
        ('NVIDIA', 'Graphics processor and AI computing company'),
        ('Logitech', 'Computer peripherals and accessories manufacturer'),
        ('Western Digital', 'Data storage solutions provider'),
    ]

    for name, description in brands:
        Brand.objects.create(name=name, description=description)

def remove_initial_data(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    Brand = apps.get_model('products', 'Brand')
    Category.objects.all().delete()
    Brand.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_data, remove_initial_data),
    ]
